---
title: "Assignment 2"
author: "Victor Asum"
date: "2024-11-21"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Is there an association between a citizen's living condition and their perception of civil servant corruption?*


*Is the perception of media freedom associated with citizens' satisfaction with democracy in Ghana?*


# SECTION 1:
```{r}
library(descr)
library(haven)
GH_AFRO_9 <- read_sav("C:/Users/AiAsum/Downloads/afrobarometer_release-dataset_gha_r9_en_2023-04-01.sav")

```


# Section 2: 
```{r}

vars <- c("Q4B", "Q38C", "Q33H", "Q31", "Q86C", "Q7A") 
cleanData <- GH_AFRO_9[vars]
save(cleanData, file='PA2_Research.RDATA')

```


# Section three: Error handling of Variables 

```{r}
cleanData$Q4B <- as.character(cleanData$Q4B)

cleanData$Q4B[cleanData$Q4B == "9" ] <- NA
cleanData$Q4B[cleanData$Q4B == "-1" ] <- NA
cleanData$Q4B[cleanData$Q4B == "8" ] <- NA

cleanData$Q4B <- factor(cleanData$Q4B,
                         levels = c("1", "2", "3", "4", "5"),
                         labels = c("Very bad", "Fairly bad", "Neither good nor bad",
                                    "Fairly good", "Very good"))



### Coding and Error Handling for Q38C

cleanData$Q38C <- as.character(cleanData$Q38C)
cleanData$Q38C[cleanData$Q38C == "8"] <- NA
cleanData$Q38C[cleanData$Q38C == "9"] <- NA
cleanData$Q38C[cleanData$Q38C == "-1"] <- NA

cleanData$Q38C <- factor(cleanData$Q38C,
                         levels = c("0", "1", "2", "3"),
                         labels = c("None", "Some of them", "Most of them", "All of them"))



# Second research questions
### Coding and Error Handling for Q33H

cleanData$Q33H <- as.character(cleanData$Q33H)

cleanData$Q33H[cleanData$Q33H == "8"] <- NA
cleanData$Q33H[cleanData$Q33H == "9"] <- NA
cleanData$Q33H[cleanData$Q33H == "-1"] <- NA

cleanData$Q33H <- factor(cleanData$Q33H,
                         levels = c("0", "1", "2", "3"),
                         labels = c("Not at all free", "Not very free",
                                    "Somewhat free", "Completely free"))

### Coding and Error Handling for Q31

cleanData$Q31 <- as.character(cleanData$Q31)

cleanData$Q31[cleanData$Q31 == "8"] <- NA
cleanData$Q31[cleanData$Q31 == "9"] <- NA
cleanData$Q31[cleanData$Q31 == "-1"] <- NA

cleanData$Q31 <- factor(cleanData$Q31,
                        levels = c("0", "1", "2", "3", "4"),
                        labels = c("Ghana is not a democracy", "Not at all satisfied", 
                                   "Not very satisfied", "Fairly satisfied", 
                                   "Very satisfied"))


freq(cleanData$Q4B, cex.names=0.5, ylab = "Frequency", xlab = "Citizen's Living Condition")
freq(cleanData$Q38C, cex.names=0.5, ylab = "Frequency", xlab = "Citizen's Perceive Corruption")
freq(cleanData$Q33H, cex.names=0.5, ylab = "Frequency", xlab = "Citizen's Perceive of Media freedom")
freq(cleanData$Q31, cex.names=0.5, ylab = "Frequency", xlab = "Citizen's Satisfaction of Democracy")



```


# Section 4 - 
```{r}

```


# Section 5

```{r}

# Is there an association between a citizen's living condition and their perception of civil servant corruption? Q4B -- present living, Q38C corruption of civil servant
# Living Condition Explainatory
# Curruption Reponse
# Table to show proportion of living conditions in each corruption variable
living_corruption_table <- table(cleanData$Q38C, cleanData$Q4B)

living_corruption_table_colProp <-prop.table(living_corruption_table, 2) 
round(living_corruption_table_colProp, 3)

# Second Research
#Is the perception of media freedom associated with citizens' satisfaction with democracy in #Ghana?
# Satisfaction of democracy - response
# Media freesom is expla
media_democracy <- table(cleanData$Q31, cleanData$Q33H)

media_democracy_colProp <-prop.table(media_democracy, 2) 
round(media_democracy_colProp, 3)


```

# SECTION 4:
```{r}
colors1 <- c("#1F4529", "#47663B", "#E8ECD7", "#EED3B1")
colors2 <- c("#181C14", "#FC8F54", "#697565", "#ECDFCC", "#AA5486")

barplot(
  living_corruption_table_colProp, 
  beside = TRUE,                
  cex.names = 0.6,
  ylim = c(0, 0.8),
  col = colors1,  
  xlab = "Citizen's Living Condition", 
  ylab = "Proportion of Citizen's Perception of Corruption of Civil Servants"
)

legend(
  "top",   
  legend = rownames(living_corruption_table_colProp),
  fill = colors1,
  title = "Perception Corruption Level",
  cex = 0.6
)


barplot(
  media_democracy_colProp, 
  beside = TRUE,                
  cex.names = 0.6,
  ylim = c(0, 0.65),
  col = colors2,  
  xlab = "Perception of Freedom of Media", 
  ylab = "Proportion of Satisfaction of Democracy"
)

legend(
  "top",   
  legend = rownames(media_democracy_colProp),
  fill = colors2,
  title = "Satisfaction of Democracy",
  cex = 0.6
)


```

